[package]
name = "flatbuffer_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
flatbuffers = { version ="25.12.19", default-features = false }
paste = "1.0.15"
rand = "0.10.0"
[build-dependencies]
flatbuffers-build = "0.2.4+flatc-25.12.19"
